<?php

/*
 * Implementation of hook_nodeapi().
 */

function apw_discussion_page_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {

    if ('view' == $op && $node->build_mode === NODE_BUILD_NORMAL) {

        $content = $node->content['body']['#value'];

        if (1375 == $node->nid) {//this is the discussion page
            $node->content['body'] = array('#value' => $content . views_embed_view('discussion_paper'));
        }
    }

    if ($node->type === 'paper_extract') {
        //$node->field_paper_extract_paper[0]['safe']['title']
        drupal_set_breadcrumb(array('<a href="/page/home">Home</a>', l(t('Discussion Page'), 'page/discussion-page'), $node->title) );

        $content = $node->content['body']['#value'];
        $node->content['body'] =  array('#value' => 'Published in the paper : <span style="font-size: 120%;"><i>' . $node->field_paper_extract_paper[0]['safe']['title'] . '</i></span>' . $content);
    }
}
