<?php

// $Id$
/**
 * @file
 * Fetches the related news articles
 */

function apw_translation_view_node_view($node, $view_mode, $langcode) {
if ('full' === $view_mode) {

        if ('page' == $node->type) {
            global $language;

        if (932 == $node->nid || 
                1617 == $node->nid || 
                1618 == $node->nid || 
                1619 == $node->nid) {
	    drupal_goto('user/register'); 
        }
	
            if (2 == $node->nid) {//this is the home page
                    if('en' !== $language->language) {
			drupal_goto('node/' . _translation_nodelink(2));
		    }
            }
            if (3 == $node->nid) {//this is the global fund grants page
                //drupal_goto('node/' . _translation_nodelink(4));
            }
            if (1232 == $node->nid) {//this is the publications page
                //drupal_goto('node/' . _translation_nodelink(934));
            }

            if (819 == $node->nid) {//this is the about us page
                drupal_goto('node/' . _translation_nodelink(922));
            }
            if (1244 == $node->nid) {//this is the who is involved page
                drupal_goto('node/' . _translation_nodelink(821));
            }
	    
	                if (1683 == $node->nid) {//this is the who is involved page
                drupal_goto('node/' . _translation_nodelink(1679));
}
	                if (1953 == $node->nid) {//this is the who is involved page
                drupal_goto('node/' . _translation_nodelink(1945));
}
        }
    }
}

function apw_translation_view_form_contact_mail_page_alter() {
    global $language;

    drupal_set_title(i18nstrings('menu:item:751:title', 'Contact Us', $language->language));
}

function _translation_nodelink($nid) {
    global $language;
    // Look for a translated version of this node in the current site selected language
    $result = db_query("SELECT n2.nid, n2.title
       FROM {node} n1, {node} n2
       WHERE n1.tnid = n2.tnid
       AND n1.tnid != 0
       AND n1.nid = :nid
       AND n2.language = :lang", array(':nid' => $nid, ':lang' => $language->language));
    
    $node = $result->fetchObject();

    if ($node) {
        $nid = $node->nid;
    }

    return $nid;
}

