<?php

// $Id$
/**
 * @file
 * Fetches the publications nodes
 */
function apw_publication_view_node_view($node, $view_mode, $langcode) {

    if('full' === $view_mode) {
        $publication_markup = null;
           if (934 == $node->nid || 
                   1611 == $node->nid || 
                   1612 == $node->nid || 
                   1613 == $node->nid) {//this is the guides page. nid is 789
                //$guides = _aidspan_publications(2, 4); //guides have id 2 in the system {publication_type} relation and category of other
                // we need to get all the guides in the systems
                $guides = _aidspan_publications(array(2)); //guides have id 2 in the system {publication_type} relation and category of other
                
                $publication_markup = theme('publication_list_teaser', array('category' => t('Guides'), 'publications' => $guides));
            }
            if (2044 == $node->nid || 
                    2045 == $node->nid || 
                    2046 == $node->nid ||
                    2047 == $node->nid) {//this is the reports page.
                $reports = _aidspan_publications(array(1, 3)); //reports have id 1 in the system {publication_type} relation
               
                $publication_markup = theme('publication_list_teaser', array('category' => t('Reports'), 'publications' => $reports));
            }

            $node->content['publication_outline_section'] = array (
                  '#markup' => $publication_markup,
                  '#weight' => 1,
                );
    }
}

function apw_publication_view_theme() {
    return array(
        'publication_list_teaser' => array('variables' => array('category' => NULL, 'publications' => NULL))
    );
}

function _aidspan_publications($publication_type_ids, $category = null) {

    $guide_cat_sql = '';
    if ($category) {
        $guide_cat_sql = ' AND wctp.field_guide_category_id_value = ' . $category;
    }

    $sql = "SELECT
node.nid AS node_id,
node.title AS publication_title,
p_author.field_publication_author_value AS publication_author,
p_date.field_publication_date_value AS publication_date,
p_type.field_publication_type_id_value AS wctp_field_publication_type,
p_description.field_publication_description_value AS publication_description
FROM web_node node
LEFT JOIN web_field_data_field_publication_author p_author ON node.nid = p_author.entity_id
LEFT JOIN web_field_data_field_publication_date p_date ON node.nid = p_date.entity_id
LEFT JOIN web_field_data_field_publication_type_id p_type ON node.nid = p_type.entity_id
LEFT JOIN web_field_data_field_publication_description p_description ON node.nid = p_description.entity_id
WHERE node.type in ('publication') AND node.status = 1 
AND p_type.field_publication_type_id_value IN (" . implode(", ", $publication_type_ids) . ') ' . $guide_cat_sql .
            " ORDER BY p_date.field_publication_date_value DESC";

    $result = db_query($sql);

    $publication_info = array();
    
    $i = 0;
    
    foreach ($result as $data) {
        $row = _prep_publication_properties($data);

        $publication_info[$i] = $row;

        $i++;  
    }

    return $publication_info;
}

function _prep_publication_properties($data) {
    
        $row = array();

        $row[] = $data->node_id;
        $row[] = $data->publication_title;
        $row[] = $data->publication_author;
        $row[] = $data->publication_date;
        $row[] = $data->publication_description;

        //get the files that are linked to this publication
        $sql = "SELECT wcfpf.field_publication_file_description description, wf.filename,
            wf.uri filepath, wf.filesize
            FROM web_field_data_field_publication_file wcfpf
INNER JOIN web_file_managed wf ON wcfpf.field_publication_file_fid = wf.fid
WHERE wcfpf.entity_id = " . $data->node_id .
                " ORDER BY wf.filename";

        $files = db_query($sql);
        
        $downloads = array();
        $downloads[''] = array();

        foreach ($files as $file) {
            $lang = get_publication_lang($file->filepath);
            
            $downloads[$file->description][$lang][] = file_create_url($file->filepath);
        }

        $row[] = $downloads;  
        
        return $row;
}

function get_publication_lang($filename) {
    $lang = 'English';

    if (strpos($filename, '-fr.') || strpos($filename, '-fr_')) {
        $lang = 'Français';
    }
    if (strpos($filename, '-es.') || strpos($filename, '-es_')) {
        $lang = 'Español';
    }
    if (strpos($filename, '-ru.') || strpos($filename, '-ru_')) {
        $lang = 'Русский';
    }

    return $lang;
}
